//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Time {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Time.IWorkTime")]
    public interface IWorkTime {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkTime/GetTime", ReplyAction="http://tempuri.org/IWorkTime/GetTimeResponse")]
        int GetTime(int workerID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkTimeChannel : ConsoleApplication1.Time.IWorkTime, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkTimeClient : System.ServiceModel.ClientBase<ConsoleApplication1.Time.IWorkTime>, ConsoleApplication1.Time.IWorkTime {
        
        public WorkTimeClient() {
        }
        
        public WorkTimeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkTimeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkTimeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkTimeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetTime(int workerID) {
            return base.Channel.GetTime(workerID);
        }
    }
}
